import '../../../../core/network/base_remote_data_source.dart';
import '../../../../core/network/dio_client.dart';
import '../../../../core/constants/api_endpoints.dart';
import '../../../booking/data/models/booking_model.dart';
import '../../domain/usecases/params/accept_emergency_params.dart';

abstract class EmergencyRemoteDataSource {
  Future<BookingModel> acceptEmergency(AcceptEmergencyParams params);
}

class EmergencyRemoteDataSourceImpl extends BaseRemoteDataSource
    implements EmergencyRemoteDataSource {
  final DioClient dioClient;
  EmergencyRemoteDataSourceImpl(this.dioClient);

  @override
  Future<BookingModel> acceptEmergency(AcceptEmergencyParams params) async {
    final response = await dioClient.post(
      '${ApiEndpoints.providerEmergencies}/${params.dispatchId}/accept',
    );

    // Extract the booking reference generated by Laravel Action
    final String reference = response.data['data']['bookingReference'];

    // Fetch full entity seamlessly to hydrate the UI
    final fullBooking = await dioClient.get(
      '${ApiEndpoints.providerBookings}/$reference',
    );
    return BookingModel.fromJson(fullBooking.data['data'] ?? fullBooking.data);
  }
}
