// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS9BZx4fNqhQ3nHQV12j5uUuYIf0M2QqE',
    appId: '1:803917554394:android:af10fc77db6b5bc569fbe3',
    messagingSenderId: '803917554394',
    projectId: 'sevika-app-717b4',
    storageBucket: 'sevika-app-717b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuXoZoOlMLfZ4Cdpn1nKbpY_4f_L816Xk',
    appId: '1:803917554394:ios:0330e57b7d40571069fbe3',
    messagingSenderId: '803917554394',
    projectId: 'sevika-app-717b4',
    storageBucket: 'sevika-app-717b4.firebasestorage.app',
    androidClientId: '803917554394-k59mebbfa6bss7vdth3a2t1mnjm1ifnc.apps.googleusercontent.com',
    iosClientId: '803917554394-3h4to7vield84ah284866rua559a124g.apps.googleusercontent.com',
    iosBundleId: 'com.sevika.sevikaPro',
  );
}
